### ISSUE TITLE
Getting error: Error: Cannot find module 'react-test-renderer/shallow' 

### ISSUE THREAD

**Issue by ezmiller** [bruderstein/unexpected-react#47]
After upgrading to v4.1.0, I am getting the above error. Does anyone know what might be going on here? I am running my tests using `mocha-webpack`, and it kind of looks as though this error is arising as mocha-webpack tries to build the testing bundles...

**Comment by ezmiller** [comment]
I seem to have solved this temporarily by installing the react-test-render explicitly: `npm i -D react-test-renderer`.

**Comment by bruderstein** [comment]
react-test-renderer is now a peerDep of unexpected-react from version 5.
